### ISSUE TITLE
Wrong package dimensions!

### ISSUE THREAD

**Issue by elcojacobs** [oakwhiz/STM32F030K6T6#1]
I used this library in a new design.
Ordered boards and a stencil for a prototype, applied solder paste and luckily wanted to place this part first.

Found out the part didn't match the footprint. The part is LQFP 7x7, this library is LQFP 5x5. As far as I have been able to find STM32F0 doesn't exist in LQFP 5x5.

The part exists in a QFN 5x5 package, but the pinout is slightly different. The two ground pins on the 7x7 package are changed to IO pins and GND is moved to the exposed pad.

So I binned my boards and will redesign and order new PCBs.

Should have double checked, but I didn't realize LQFP32 came in different sizes.

**Comment by kiryam** [comment]
wrong footprint, confirm

**Comment by 0xDBFB7** [comment]
Goddammit. I just got tripped up by this too. STM32F051K6Ux series is very similar in pinout, and I believe I can bodge it into place. I've submitted a pull request with what I hope is a fixed package. @oakwhiz could you please accept the merge so nobody else has issues? Thanks a lot.

**Comment by elcojacobs** [comment]
Sorry to hear that. I have a hardware tested package too, which I can send over for comparison too.

**Comment by 0xDBFB7** [comment]
@elcojacobs that would be great, if you don't mind....

You can drop it here if it's easier: 
 https://drive.google.com/drive/folders/1uRD02_Hx2o399GkrKzJnrV6LCrgeTTay?usp=sharing
